# Site settings
title: Duct Tape and Raspberry Pis
email: dylan@hackafe.net
description: > # this means to ignore newlines until "baseurl:"
  Home automation. Cats. Cat automation? Also other things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dylwhich.com" # the base hostname & protocol for your site
twitter_username: dylwhich
github_username:  dylwhich

# Build settings
markdown: kramdown
